"""Domain constants for the Office Energy Monitoring System."""

from __future__ import annotations

from enum import Enum


class RoomName(str, Enum):
    """Three rooms that exist in the office."""

    DRAWING_ROOM = "Drawing Room"
    WORK_ROOM_1 = "Work Room 1"
    WORK_ROOM_2 = "Work Room 2"


class DeviceType(str, Enum):
    """Device categories tracked by the system."""

    FAN = "fan"
    LIGHT = "light"


class DeviceStatus(str, Enum):
    """Operational status of a device."""

    ON = "on"
    OFF = "off"


class AlertSeverity(str, Enum):
    """Severity levels for alerts."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertType(str, Enum):
    """Distinct categories of alerts generated by the engine.

    Kept separate from severity so the same alert can escalate in severity
    over its lifetime without losing the original trigger category.
    """

    AFTER_HOURS_DEVICE = "after_hours_device"
    ROOM_CONTINUOUS = "room_continuous"
    CRITICAL_POWER = "critical_power"
    OFFICE_CONSUMPTION = "office_consumption"


class AlertStatus(str, Enum):
    """Lifecycle states for an alert."""

    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    DISMISSED = "dismissed"
    RESOLVED = "resolved"


# Power ratings (watts) for device types
POWER_RATINGS = {
    DeviceType.FAN: 75,
    DeviceType.LIGHT: 20,
}

# Devices per room layout
DEVICES_PER_ROOM = {
    RoomName.DRAWING_ROOM: {"fan": 2, "light": 3},
    RoomName.WORK_ROOM_1: {"fan": 2, "light": 3},
    RoomName.WORK_ROOM_2: {"fan": 2, "light": 3},
}


# ---------------------------------------------------------------------------
# Alert engine configuration
# ---------------------------------------------------------------------------

#: How many minutes an after-hours device must remain ON before the alert
#: is first raised (INFO severity).
AFTER_HOURS_DEVICE_GRACE_MINUTES: int = 5

#: How long a device must stay continuously ON in a room before the
#: ROOM_CONTINUOUS alert is raised (regardless of office hours).
ROOM_CONTINUOUS_THRESHOLD_MINUTES: int = 120

#: Default watt threshold for the CRITICAL_POWER alert. The total office
#: draw above this value for at least :data:`CRITICAL_POWER_DWELL_SECONDS`
#: triggers the alert.
CRITICAL_POWER_THRESHOLD_W: int = 1500
CRITICAL_POWER_DWELL_SECONDS: int = 30

#: Office-wide daily energy threshold (kWh) above which the
#: OFFICE_CONSUMPTION alert fires.
OFFICE_CONSUMPTION_THRESHOLD_KWH: float = 5.0

#: How long after office hours a ROOM_CONTINUOUS alert can stay active
#: before escalating in severity.
ALERT_WARNING_AFTER_MINUTES: int = 30
ALERT_CRITICAL_AFTER_MINUTES: int = 60
ALERT_MAX_AFTER_MINUTES: int = 120

#: Default cost per kWh (USD) used when estimating the financial waste of
#: a wasteful alert. Localised via env / settings if needed.
DEFAULT_COST_PER_KWH_USD: float = 0.15

#: How many minutes between proactive Discord reminders for an
#: unacknowledged alert.
REMINDER_INTERVAL_MINUTES: int = 30

#: How many minutes a user-initiated dismiss remains in effect.
DEFAULT_DISMISS_DURATION_MINUTES: int = 30